# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3e602e06-4c4f-4fcf-8c87-06f3380fd62e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bd6f0e62-d0af-4875-b12c-3d64466da5a3".device = "/dev/disk/by-uuid/bd6f0e62-d0af-4875-b12c-3d64466da5a3";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/2DE9-40D0";
      fsType = "vfat";
    };

  fileSystems."/home/darksome/steam" =
    { device = "/dev/disk/by-path/pci-0000:03:00.0-nvme-1-part3";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
