theme = "github_dark"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
q = "collapse_selection"
Q = "keep_primary_selection"

w = "change_selection"

a = "insert_mode"
A = "insert_at_line_start"
C-a = "goto_first_nonwhitespace"
C-A = "extend_to_line_start"

# Paragraph/word navigation/selection 

e = "goto_prev_paragraph"
E = "extend_line_above"

d = "goto_next_paragraph"
D = "extend_line_below"

s = "move_prev_word_start"
S = "extend_prev_word_start"
C-s = "move_prev_long_word_start"
C-S = "extend_prev_long_word_start"

f = "move_next_word_end"
F = "extend_next_word_end"
C-f = "move_next_long_word_end"
C-F = "extend_next_long_word_end"

x = [":clipboard-yank", "delete_selection"]

r = "undo"
R = "redo"
C-r = "select_regex"

c = ":clipboard-yank"

v = ":clipboard-paste-after"
V = ":clipboard-paste-before"
C-v = ":clipboard-paste-replace"

t = "goto_definition"
b = "select_mode"

y = "jump_forward"

h = "jump_backward"

k = "move_line_down"
K = "extend_line_down"

i = "move_line_up"
I = "extend_line_up"

j = "move_char_left"
J = "extend_char_left"

l = "move_char_right"
L = "extend_char_right"

"," = "no_op"

"p" = "command_mode"

";" = "append_mode"
":" = "insert_at_line_end"
"C-;" = "goto_line_end"
"C-:" = "extend_to_line_end"

"ret" = ["add_newline_below", "move_line_down"]
S-ret = ["add_newline_above", "move_line_up"]

u = "find_prev_char"
U = "extend_prev_char"
A-u = "till_prev_char"
A-U = "extend_till_prev_char"

o = "find_next_char"
O = "extend_next_char"
A-o = "find_till_char"
A-O = "extend_till_char"

[keys.normal.space]
Q = ":quit!"
q = ":quit"
s = ":write"
S = ":wq"

[keys.select]
j = "extend_char_left"
i = "extend_line_up"
k = "extend_line_down"
l = "extend_char_right"

I = "no_op"
J = "no_op"
L = "no_op"
K = "no_op"

s = "extend_prev_word_start"
C-s = "extend_prev_long_word_start"
f = "extend_next_word_end"
C-f = "extend_next_long_word_end"
e = "extend_line_above"
d = "extend_line_below"

c = [":clipboard-yank", "normal_mode"]

x = [":clipboard-yank", "delete_selection", "normal_mode"]

[keys.insert]
C-i = "move_line_up"
C-j = "move_char_left"
C-k = "move_line_down"
C-l = "move_char_right"

"C-;" = "goto_line_end_newline"
