theme = "github_dark"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
o = "goto_prev_paragraph"
e = "goto_next_paragraph"
i = "move_prev_word_start"
a = "move_next_word_end"

t = "move_line_down"
d = "move_line_up"
h = "move_char_left"
s = "move_char_right"

y = "goto_first_nonwhitespace"
u = "goto_line_end"

"*" = "goto_file_start"
"@" = "goto_last_line"

l = "insert_mode"
w = "append_mode"

space = "select_mode"
esc = ":write"

c = "change_selection"
j = ":clipboard-yank"
k = ":clipboard-paste-after"
"(" = ":clipboard-paste-replace"
K = ":clipboard-paste-replace"
backspace = "delete_selection"
x = [":clipboard-yank", "delete_selection"]
g = "undo"
G = "redo"

"p" = "search"
"P" = "global_search"

# shared

"tab" = "indent"
"S-tab" = "unindent"
"ret" = ["add_newline_below", "move_line_down"]

">" = "search_next"
")" = "search_prev"

"v" = "command_mode"

n = "goto_definition"
f = "jump_forward"
r = "jump_backward"

"," = "file_picker"
"H" = "file_picker_in_current_directory"

"=" = "code_action"
"}" = "rename_symbol"
"?" = "last_picker"
":" = "diagnostics_picker"
D = "workspace_diagnostics_picker"
"q" = ":quit"
"C-q" = ":q!"

[keys.select]
y = "extend_to_line_start"

o = "extend_line_above"
e = "extend_line_below"
i = "extend_prev_word_start"
a = "extend_next_word_end"

t = "extend_line_down"
d = "extend_line_up"
h = "extend_char_left"
s = "extend_char_right"

u = "extend_to_line_end"

"*" = "select_all"
"@" = "select_all"

c = "change_selection"
j = [":clipboard-yank", "normal_mode", "collapse_selection"]
k = [":clipboard-paste-replace", "normal_mode", "collapse_selection"]
"(" = [":clipboard-paste-replace", "normal_mode", "collapse_selection"]
K = [":clipboard-paste-replace", "normal_mode", "collapse_selection"]
backspace = ["delete_selection", "normal_mode"]
x = [":clipboard-yank", "delete_selection", "normal_mode"]
p = ["select_regex", "normal_mode"]
space = ["normal_mode", "collapse_selection"]

# shared

"tab" = "indent"
"S-tab" = "unindent"
"ret" = ["add_newline_below", "move_line_down"]

">" = "search_next"
")" = "search_prev"

"v" = "command_mode"

n = "goto_definition"
f = "jump_forward"
r = "jump_backward"

"," = "file_picker"
"H" = "file_picker_in_current_directory"

"=" = "code_action"
"}" = "rename_symbol"
"?" = "last_picker"
":" = "diagnostics_picker"
D = "workspace_diagnostics_picker"
"q" = ":quit"
"C-q" = ":q!"

[keys.insert]
esc = ["normal_mode", ":write"]

[keys.normal.b]
i = "goto_implementation"
d = "goto_definition"
t = "goto_type_definition"
r = "goto_reference"
