theme = "github_dark"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
c = "goto_first_nonwhitespace"

o = "goto_prev_paragraph"
e = "goto_next_paragraph"
i = "move_prev_word_start"
a = "move_next_word_end"

t = "move_line_down"
d = "move_line_up"
h = "move_char_left"
s = "move_char_right"

n = "goto_line_end"

l = "change_selection"
k = ":clipboard-yank"
r = ":clipboard-paste-after"
")" = ":clipboard-paste-replace"
"backspace" = "delete_selection"
"j" = [":clipboard-yank", "delete_selection"]
P = "select_regex"

b = "select_mode"

q = "collapse_selection"
"%" = "keep_primary_selection"

z = "search_next"
"$" = "search_prev"

y = "insert_mode"
# A = "insert_at_line_start"


u = "undo"
"+" = "redo"


"tab" = "goto_definition"
v = "command_mode"

D = "jump_forward"
T = "jump_backward"


"p" = "search"

w = "append_mode"
# ":" = "insert_at_line_end"

"ret" = ["add_newline_below", "move_line_down"]
# S-ret = ["add_newline_above", "move_line_up"]

[keys.select]
c = "extend_to_line_start"

o = "extend_line_above"
e = "extend_line_below"
i = "extend_prev_word_start"
a = "extend_next_word_end"

t = "extend_line_down"
d = "extend_line_up"
h = "extend_char_left"
s = "extend_char_right"

n = "extend_to_line_end"

l = "change_selection"
k = [":clipboard-yank", "normal_mode", "collapse_selection"]
r = [":clipboard-paste-replace", "normal_mode", "collapse_selection"]
"backspace" = ["delete_selection", "normal_mode"]
j = [":clipboard-yank", "delete_selection", "normal_mode"]
p = ["select_regex", "normal_mode"]

[keys.normal.space]
Q = ":quit!"
q = ":quit"
s = ":write"
S = ":wq"
